environments:
  dev:
    values:
      - env: dev

  prod:
    values:
      - env: prod


releases:
  {{ if eq .Environment.Name "dev" }}
  - name: john-dev
    chart: ./nginx-pod-chart
    values:
      - john.yaml
    namespace: greeting
  {{ end }}

  {{ if eq .Environment.Name "prod" }}
  - name: john-prod
    chart: ./nginx-pod-chart
    values:
      - john.yaml
    namespace: greeting
  - name: mike-prod
    chart: ./nginx-pod-chart
    values:
      - mike.yaml
    namespace: greeting
  - name: sam-prod
    chart: ./nginx-pod-chart
    values:
      - sam.yaml
    namespace: greeting
  {{ end }}
