apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.TAGS.name }}-pod-{{ .Release.Name }}-{{ .Release.Revision | default "1" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
    environment: {{ .Values.env }}
spec:
  containers:
    - name: nginx
      image: nginx:{{ .Values.TAG }}
      env:
        - name: MESSAGE
          value: "{{ .Values.MESSAGE }}"
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
